[package]
name = "secure-process-memory"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.175"
sysinfo = "0.37.0"


[target.'cfg(target_os = "macos")'.dependencies]
windows = "0.62.0"
